### PR TITLE
Update to nix 0.20.

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by eldruin** [comment]
Sounds good to me but nix 0.20 requires increasing the MSRV to 1.40.
Could you also increase it and add an entry to the changelog?

**Comment by eldruin** [comment]
Great, thanks!
Any objections to raising the MSRV @rust-embedded/embedded-linux? I do not think we have a choice, though.

**Review by eldruin — APPROVED** [review]

**Review by posborne — APPROVED** [review]

**Comment by posborne** [comment]
No objection @eldruin.  On next release, we'll bump the crate version as well.  Thanks @m-ou-se!

@bors r+

**Comment by posborne** [comment]
Ooops, bors r+

**Pull request merged**
