### PR TITLE
travis: add travis postback for rust-embedded-bot

### PR DESCRIPTION
**Pull request by posborne**
Also update the versions of rust being tested.

CC @nastevens

### CODE REVIEW

**Comment by nastevens** [comment]
@rust-embedded-bot r+

**Comment by nastevens** [comment]
@rust-embedded-bot r+

**Comment by nastevens** [comment]
Alright, g-damn gremlins.

Originally, nothing was working for me, so I logged in to Heroku to get the logs. When I logged in, Heroku asked for GitHub repo permissions. Immediately after I logged in, it still didn't seem like Homu was seeing my approvals. If I went to the Homu page directly and clicked "Synchronize" I would get an internal server error.

Fast forward about 30 minutes of futzing, and now all the branches seem to be working except for `rust-spidev`, which gives the error:

```
2016-05-02T11:51:53.372638+00:00 app[web.1]: repo_label: rust-embedded/rust-spidev
2016-05-02T11:51:53.372654+00:00 app[web.1]: DEBUG:homu.server.queue:repo_label: rust-embedded/rust-spidev
2016-05-02T11:51:55.934709+00:00 app[web.1]: state: {'repo_label': 'rust-embedded/rust-spidev', 'cmd': 'synch'}
2016-05-02T11:51:55.934727+00:00 app[web.1]: DEBUG:homu.server.callback:state: {'repo_label': 'rust-embedded/rust-spidev', 'cmd': 'synch'}
2016-05-02T11:51:56.097551+00:00 app[web.1]: Traceback (most recent call last):
2016-05-02T11:51:56.097583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/bottle.py", line 862, in _handle
2016-05-02T11:51:56.097585+00:00 app[web.1]:     return route.call(**args)
2016-05-02T11:51:56.097585+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/bottle.py", line 1732, in wrapper
2016-05-02T11:51:56.097586+00:00 app[web.1]:     rv = callback(*a, **ka)
2016-05-02T11:51:56.097586+00:00 app[web.1]:   File "/app/.heroku/src/homu/homu/server.py", line 136, in callback
2016-05-02T11:51:56.097587+00:00 app[web.1]:     return synch(user_gh, state, repo_label, repo_cfg, repo)
2016-05-02T11:51:56.097587+00:00 app[web.1]:   File "/app/.heroku/src/homu/homu/server.py", line 627, in synch
2016-05-02T11:51:56.097588+00:00 app[web.1]:     if not repo.is_collaborator(user_gh.user().login):
2016-05-02T11:51:56.097589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/github3/repos/repo.py", line 979, in is_collaborator
2016-05-02T11:51:56.097589+00:00 app[web.1]:     return self._boolean(self._get(url), 204, 404)
2016-05-02T11:51:56.097590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/github3/models.py", line 121, in _boolean
2016-05-02T11:51:56.097590+00:00 app[web.1]:     raise GitHubError(response)
2016-05-02T11:51:56.097591+00:00 app[web.1]: github3.models.GitHubError: 403 Must have push access to view repository collaborators.
```

Best I can figure, there is some connection between me authorizing Heroku access to my repos and things starting to work, but I can't imagine why...

**Comment by nastevens** [comment]
@rust-embedded-bot r+

**Comment by nastevens** [comment]
Definitely seems to be a permissions-type issue on this repo. Does rust-embedded-bot need to have push permissions added?

**Comment by posborne** [comment]
@rust-embedded-bot r=nastevens

**Comment by posborne** [comment]
@rust-embedded-bot r=nastevens

**Pull request merged**
